<a href="https://colab.research.google.com/github/ulrikSebastienR/2021-Coding-Basic/blob/main/Operations_on_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Reference Python Help Files
#Creating DF, setting and getting values by df.loc
import pandas as pd
from sklearn import datasets
print(dir(pd))
print(dir(pd.DataFrame))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'comp

In [3]:
#print(help(pd.DataFrame.loc))

In [4]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_class

In [5]:
wine = datasets.load_wine()
print(type(wine))
for i in wine:
  print(i)
  print(wine[i])

<class 'sklearn.utils.Bunch'>
data
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
target
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
target_names
['class_0' 'class_1' 'class_2']
DESCR
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in

In [6]:
df_wine = pd.DataFrame(wine.data, columns=wine.feature_names)
df_wine['target'] = wine.target
print(df_wine, '\n', df_wine.describe())

     alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[17

In [7]:
df = pd.DataFrame([[1,2],[4,5],[6,7]],index=['cobra','viper','sidewinder'],columns=['max_speed','shield'])
df

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          6       7

In [8]:
df.loc['viper'] # axis = 0 is considered to be the original axis

max_speed    4
shield       5
Name: viper, dtype: int64

In [9]:
df_wine.loc[23] # row number 23

alcohol                           12.85
malic_acid                         1.60
ash                                2.52
alcalinity_of_ash                 17.80
magnesium                         95.00
total_phenols                      2.48
flavanoids                         2.37
nonflavanoid_phenols               0.26
proanthocyanins                    1.46
color_intensity                    3.93
hue                                1.09
od280/od315_of_diluted_wines       3.63
proline                         1015.00
target                             0.00
Name: 23, dtype: float64

In [10]:
df.loc[:,'max_speed'] # To access a column or any other dimension, we need to define all axes.

cobra         1
viper         4
sidewinder    6
Name: max_speed, dtype: int64

In [11]:
df_wine.loc[:,'proline']

0      1065.0
1      1050.0
2      1185.0
3      1480.0
4       735.0
        ...  
173     740.0
174     750.0
175     835.0
176     840.0
177     560.0
Name: proline, Length: 178, dtype: float64

In [12]:
df_wine.loc[173,'alcohol'] #row-column value

13.71

In [13]:
df_wine.at[173,'alcohol'] #can also be accessed using DataFrame.at

13.71

In [14]:
df_wine.loc[171:174,['alcohol','proline']] #accessing a selection

alcohol  proline
171    12.77    470.0
172    14.16    660.0
173    13.71    740.0
174    13.40    750.0

In [15]:
df.loc[[False,False,True]] #default is always row-wise and False means we don't want that row

max_speed  shield
sidewinder          6       7

In [16]:
df.loc[df['max_speed'] > 1]

max_speed  shield
viper               4       5
sidewinder          6       7

In [17]:
df['max_speed'] > 2

cobra         False
viper          True
sidewinder     True
Name: max_speed, dtype: bool

In [18]:
df.loc[df['max_speed'] >1, ['shield']]

shield
viper            5
sidewinder       7

In [19]:
df.loc[lambda df: df['shield']==7]

max_speed  shield
sidewinder          6       7

In [20]:
# Setting Values
df.loc[['viper', 'sidewinder'], ['shield']] = 50
df

max_speed  shield
cobra               1       2
viper               4      50
sidewinder          6      50

In [21]:
#for further but similar practice df.iloc
#if needed, multiindex DataFrame and methods for them do exist.

In [22]:
#Sorting by value and index sort_byvalue and sort_byindex
import pandas as pd
import numpy as np
data = {'name':['david','gru','kid','ram','ilya'],
'age': [24, 10, 3, np.nan, 79],
'bad health':['False', 'True', 'Excellent', 'Excellent', 'bad']
}
print(data.keys())
df = pd.DataFrame(data, columns=data.keys())
print(df)

print(df.count())
print(df.count(axis=1),'\n')

print(df.sort_values(by='age',inplace=True)) #Updates df and returns a new df for inplace=True.
print(df, '\n')
print(df.sort_values(by='name',inplace=False)) # Updates df but doesn't return a new df for inplace = False.
print(df,'\n')
print(df.sort_values(by=['name','age'])) #doesn't incorporate second variable and sorts only on the basis of first row/column name passed to it. 

dict_keys(['name', 'age', 'bad health'])
    name   age bad health
0  david  24.0      False
1    gru  10.0       True
2    kid   3.0  Excellent
3    ram   NaN  Excellent
4   ilya  79.0        bad
name          5
age           4
bad health    5
dtype: int64
0    3
1    3
2    3
3    2
4    3
dtype: int64 

None
    name   age bad health
2    kid   3.0  Excellent
1    gru  10.0       True
0  david  24.0      False
4   ilya  79.0        bad
3    ram   NaN  Excellent 

    name   age bad health
0  david  24.0      False
1    gru  10.0       True
4   ilya  79.0        bad
2    kid   3.0  Excellent
3    ram   NaN  Excellent
    name   age bad health
2    kid   3.0  Excellent
1    gru  10.0       True
0  david  24.0      False
4   ilya  79.0        bad
3    ram   NaN  Excellent 

    name   age bad health
0  david  24.0      False
1    gru  10.0       True
4   ilya  79.0        bad
2    kid   3.0  Excellent
3    ram   NaN  Excellent


In [23]:
df = pd.DataFrame({'CompanyName': {0: 'Customer1', 1: 'Customer1', 2: 'Customer2', 3: 'Customer3', 4: 'Customer1', 5: 'Customer3', 6: 'Customer3', 7: 'Customer3', 8: 'Customer4'}, 'HighPriority': {0: 'Yes', 1: 'Yes', 2: 'No', 3: 'No', 4: 'No', 5: 'No', 6: 'Yes', 7: 'Yes', 8: 'No'}, 'QualityIssue': {0: 'User', 1: 'User', 2: 'User', 3: 'Equipment', 4: 'Neither', 5: 'User', 6: 'User', 7: 'Equipment', 8: 'User'}})
df

CompanyName HighPriority QualityIssue
0   Customer1          Yes         User
1   Customer1          Yes         User
2   Customer2           No         User
3   Customer3           No    Equipment
4   Customer1           No      Neither
5   Customer3           No         User
6   Customer3          Yes         User
7   Customer3          Yes    Equipment
8   Customer4           No         User

In [24]:
print(df.sort_values(by='CompanyName', ascending=False,inplace=True))
df

None


CompanyName HighPriority QualityIssue
8   Customer4           No         User
3   Customer3           No    Equipment
5   Customer3           No         User
6   Customer3          Yes         User
7   Customer3          Yes    Equipment
2   Customer2           No         User
0   Customer1          Yes         User
1   Customer1          Yes         User
4   Customer1           No      Neither

In [25]:
data = {
	'CompanyName':['Customer1','Customer1','Customer2','Customer3','Customer2'],
	'HighPriority':['Yes','Yes','No','Yes','No'],
	'QualityIssue':['User','Equipment','User','User','Equipment']
}
df = pd.DataFrame(data)
df

CompanyName HighPriority QualityIssue
0   Customer1          Yes         User
1   Customer1          Yes    Equipment
2   Customer2           No         User
3   Customer3          Yes         User
4   Customer2           No    Equipment

In [26]:
df.sort_values(by='CompanyName')

CompanyName HighPriority QualityIssue
0   Customer1          Yes         User
1   Customer1          Yes    Equipment
2   Customer2           No         User
4   Customer2           No    Equipment
3   Customer3          Yes         User

In [30]:
df['frequency']= df.groupby('CompanyName')['CompanyName'].transform('count')
df #

CompanyName HighPriority QualityIssue  frequency
0   Customer1          Yes         User          2
1   Customer1          Yes    Equipment          2
2   Customer2           No         User          2
3   Customer3          Yes         User          1
4   Customer2           No    Equipment          2

In [32]:
df.sort_values('frequency',inplace=True,ascending=False)
df #https://stackoverflow.com/questions/30787391/sorting-entire-csv-by-frequency-of-occurence-in-one-column

CompanyName HighPriority QualityIssue  frequency
0   Customer1          Yes         User          2
1   Customer1          Yes    Equipment          2
2   Customer2           No         User          2
4   Customer2           No    Equipment          2
3   Customer3          Yes         User          1

In [44]:
import pandas as pd
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
#print(iris)
'''for i in iris:
    print(i, '\n', iris[i])'''
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target']=iris.target
print(df)
print(df.loc[[13,42,38,8]])

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]
    sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
13                4.3               3.0  

In [38]:
df.sort_values('sepal length (cm)') # I still don't understand what those two articles were about.

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
13                 4.3               3.0  ...               0.1       0
42                 4.4               3.2  ...               0.2       0
38                 4.4               3.0  ...               0.2       0
8                  4.4               2.9  ...               0.2       0
41                 4.5               2.3  ...               0.3       0
..                 ...               ...  ...               ...     ...
122                7.7               2.8  ...               2.0       2
118                7.7               2.6  ...               2.3       2
117                7.7               3.8  ...               2.2       2
135                7.7               3.0  ...               2.3       2
131                7.9               3.8  ...               2.0       2

[150 rows x 5 columns]