<a href="https://colab.research.google.com/github/ulrikSebastienR/2021-Coding-Basic/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
#https://www.kdnuggets.com/2020/07/easy-guide-data-preprocessing-python.html
#https://machinelearningmastery.com/data-preparation-for-machine-learning-7-day-mini-course/
# For simple imputer we first need to convert DF to array and then array to DF as fit and fit_transform methods only apply on arrays.
# How to simple impute without converting to and from array with df[iloc]
# KNN imputer
# RFE or recursive feature elimination
# Label Encoder
# One Hot Encoder
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'
import pandas as pd
from sklearn.impute import SimpleImputer

In [48]:
df = pd.read_csv(url) # without passing header and na_values = 'indicator of na values', we might not get the proper missing values by df.isna()
print(df)
print(df.describe())
df.isna().sum() 

     2  1   530101  38.50   66  28  ... 2.2 2.3 11300 00000 00000.1 2.4
0    1  1   534817   39.2   88  20  ...   3   2  2208     0       0   2
1    2  1   530334  38.30   40  24  ...   1   2     0     0       0   1
2    1  9  5290409  39.10  164  84  ...   2   1  2208     0       0   1
3    2  1   530255  37.30  104  35  ...   2   2  4300     0       0   2
4    2  1   528355      ?    ?   ?  ...   1   2     0     0       0   2
..  .. ..      ...    ...  ...  ..  ...  ..  ..   ...   ...     ...  ..
294  1  1   533886      ?  120  70  ...   3   2  3205     0       0   2
295  2  1   527702  37.20   72  24  ...   3   1  2208     0       0   1
296  1  1   529386  37.50   72  30  ...   2   1  3205     0       0   2
297  1  1   530612  36.50  100  24  ...   1   1  2208     0       0   1
298  1  1   534618   37.2   40  20  ...   3   2  6112     0       0   2

[299 rows x 28 columns]
               1        530101  ...      00000.1         2.4
count  299.00000  2.990000e+02  ...   299.000000  

2          0
1          0
530101     0
38.50      0
66         0
28         0
3          0
3.1        0
?          0
2.1        0
5          0
4          0
4.1        0
?.1        0
?.2        0
?.3        0
3.2        0
5.1        0
45.00      0
8.40       0
?.4        0
?.5        0
2.2        0
2.3        0
11300      0
00000      0
00000.1    0
2.4        0
dtype: int64

In [49]:
df = pd.read_csv(url,header=None, na_values='?') #Using na_values = '?' automatically fills the na_values with NaN and header = None stops header to be computed from data columns.
print(df)
print(df.describe()) # In df.describe if the row 'min' has values 0 that means there might be missing values.
print(df.isna().sum())

      0   1        2     3      4     5    6   ...   21   22  23     24  25  26  27
0    2.0   1   530101  38.5   66.0  28.0  3.0  ...  NaN  2.0   2  11300   0   0   2
1    1.0   1   534817  39.2   88.0  20.0  NaN  ...  2.0  3.0   2   2208   0   0   2
2    2.0   1   530334  38.3   40.0  24.0  1.0  ...  NaN  1.0   2      0   0   0   1
3    1.0   9  5290409  39.1  164.0  84.0  4.0  ...  5.3  2.0   1   2208   0   0   1
4    2.0   1   530255  37.3  104.0  35.0  NaN  ...  NaN  2.0   2   4300   0   0   2
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ..    ...  ..  ..  ..
295  1.0   1   533886   NaN  120.0  70.0  4.0  ...  NaN  3.0   2   3205   0   0   2
296  2.0   1   527702  37.2   72.0  24.0  3.0  ...  3.3  3.0   1   2208   0   0   1
297  1.0   1   529386  37.5   72.0  30.0  4.0  ...  NaN  2.0   1   3205   0   0   2
298  1.0   1   530612  36.5  100.0  24.0  3.0  ...  3.4  1.0   1   2208   0   0   1
299  1.0   1   534618  37.2   40.0  20.0  NaN  ...  1.0  3.0   2   6112   0 

In [50]:
import numpy as np
df_array = df.to_numpy() # To Convert to array
print(df_array, df_array.shape)
# For simple imputer we first need to convert DF to array and then array to DF as fit and fit_transform methods only apply on arrays.

[[2.00000e+00 1.00000e+00 5.30101e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.34817e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [2.00000e+00 1.00000e+00 5.30334e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 ...
 [1.00000e+00 1.00000e+00 5.29386e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.30612e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.00000e+00 1.00000e+00 5.34618e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]] (300, 28)


In [51]:
impute = SimpleImputer()
X = impute.fit_transform(df_array)
print(X)
df = pd.DataFrame(X) # A DataFrame can directly be constructed from an array.
print(df)
print(df.describe())
print(df.isna().sum())

[[2.00000e+00 1.00000e+00 5.30101e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.34817e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [2.00000e+00 1.00000e+00 5.30334e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 ...
 [1.00000e+00 1.00000e+00 5.29386e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.30612e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.00000e+00 1.00000e+00 5.34618e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]]
      0    1          2          3      4   ...   23       24   25   26   27
0    2.0  1.0   530101.0  38.500000   66.0  ...  2.0  11300.0  0.0  0.0  2.0
1    1.0  1.0   534817.0  39.200000   88.0  ...  2.0   2208.0  0.0  0.0  2.0
2    2.0  1.0   530334.0  38.300000   40.0  ...  2.0      0.0  0.0  0.0  1.0
3    1.0  9.0  5290409.0  39.100000  164.0  ...  1.0   2208.0  0.0  0.0  1.0
4    2.0  1.0   530255.0  37.300000  104.0  ...  2.0   4300.0  0.0  0.0  2.0
..   ...  ...        ...        ...    ...  ..

In [52]:
# Alternative method https://datascience.stackexchange.com/questions/51890/how-to-use-simpleimputer-class-to-replace-missing-values-with-mean-values-using

In [53]:
df1 = pd.read_csv(url,header=None, na_values='?')
print(df1)
print(df1.describe()) # In df.describe if the row 'min' has values 0 that means there might be missing values.
print(df1.isna().sum())

      0   1        2     3      4     5    6   ...   21   22  23     24  25  26  27
0    2.0   1   530101  38.5   66.0  28.0  3.0  ...  NaN  2.0   2  11300   0   0   2
1    1.0   1   534817  39.2   88.0  20.0  NaN  ...  2.0  3.0   2   2208   0   0   2
2    2.0   1   530334  38.3   40.0  24.0  1.0  ...  NaN  1.0   2      0   0   0   1
3    1.0   9  5290409  39.1  164.0  84.0  4.0  ...  5.3  2.0   1   2208   0   0   1
4    2.0   1   530255  37.3  104.0  35.0  NaN  ...  NaN  2.0   2   4300   0   0   2
..   ...  ..      ...   ...    ...   ...  ...  ...  ...  ...  ..    ...  ..  ..  ..
295  1.0   1   533886   NaN  120.0  70.0  4.0  ...  NaN  3.0   2   3205   0   0   2
296  2.0   1   527702  37.2   72.0  24.0  3.0  ...  3.3  3.0   1   2208   0   0   1
297  1.0   1   529386  37.5   72.0  30.0  4.0  ...  NaN  2.0   1   3205   0   0   2
298  1.0   1   530612  36.5  100.0  24.0  3.0  ...  3.4  1.0   1   2208   0   0   1
299  1.0   1   534618  37.2   40.0  20.0  NaN  ...  1.0  3.0   2   6112   0 

In [54]:
#df1 = impute.fit_transform(df1[:,3:21]) # slice isn't working TypeError: '(slice(None, None, None), slice(3, 21, None))' is an invalid key

In [55]:
#df1[:,0:21] TypeError: '(slice(None, None, None), slice(0, 21, None))' is an invalid key 

In [56]:
#after using iloc/loc 
print(df1.iloc[:,:22]) # Using index till 22 as the last index is left out so if we use use index till 21, column 21 will be left out.
print(df1.iloc[:,:22])
df1.iloc[:,:22] = impute.fit_transform(df1.iloc[:,:22])
print(df1.iloc[:,:22]) #Note no need of conversion df to and from array.
print(df1.isna().sum(), df1)

      0   1        2     3      4     5   ...   16   17    18    19   20   21
0    2.0   1   530101  38.5   66.0  28.0  ...  3.0  5.0  45.0   8.4  NaN  NaN
1    1.0   1   534817  39.2   88.0  20.0  ...  4.0  2.0  50.0  85.0  2.0  2.0
2    2.0   1   530334  38.3   40.0  24.0  ...  1.0  1.0  33.0   6.7  NaN  NaN
3    1.0   9  5290409  39.1  164.0  84.0  ...  3.0  NaN  48.0   7.2  3.0  5.3
4    2.0   1   530255  37.3  104.0  35.0  ...  NaN  NaN  74.0   7.4  NaN  NaN
..   ...  ..      ...   ...    ...   ...  ...  ...  ...   ...   ...  ...  ...
295  1.0   1   533886   NaN  120.0  70.0  ...  NaN  5.0  55.0  65.0  NaN  NaN
296  2.0   1   527702  37.2   72.0  24.0  ...  4.0  4.0  44.0   NaN  3.0  3.3
297  1.0   1   529386  37.5   72.0  30.0  ...  3.0  5.0  60.0   6.8  NaN  NaN
298  1.0   1   530612  36.5  100.0  24.0  ...  4.0  4.0  50.0   6.0  3.0  3.4
299  1.0   1   534618  37.2   40.0  20.0  ...  4.0  1.0  36.0  62.0  1.0  1.0

[300 rows x 22 columns]
      0   1        2     3      4     5

In [57]:
#KNN Imputer 
from sklearn.impute import KNNImputer
df = pd.read_csv(url, na_values='?', header= None)
knnimputer = KNNImputer()

In [58]:
df = knnimputer.fit_transform(df)
print(type(df), df, df.shape)
df = pd.DataFrame(df)
print(type(df),df, df.isna().sum())

<class 'numpy.ndarray'> [[2.00000e+00 1.00000e+00 5.30101e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.34817e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [2.00000e+00 1.00000e+00 5.30334e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 ...
 [1.00000e+00 1.00000e+00 5.29386e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]
 [1.00000e+00 1.00000e+00 5.30612e+05 ... 0.00000e+00 0.00000e+00
  1.00000e+00]
 [1.00000e+00 1.00000e+00 5.34618e+05 ... 0.00000e+00 0.00000e+00
  2.00000e+00]] (300, 28)
<class 'pandas.core.frame.DataFrame'>       0    1          2      3      4     5   ...   22   23       24   25   26   27
0    2.0  1.0   530101.0  38.50   66.0  28.0  ...  2.0  2.0  11300.0  0.0  0.0  2.0
1    1.0  1.0   534817.0  39.20   88.0  20.0  ...  3.0  2.0   2208.0  0.0  0.0  2.0
2    2.0  1.0   530334.0  38.30   40.0  24.0  ...  1.0  2.0      0.0  0.0  0.0  1.0
3    1.0  9.0  5290409.0  39.10  164.0  84.0  ...  2.0  1.0   2208.0  0.0  0.0  1.0
4    2.0  1.0   

In [59]:
# RFE or recursive feature elimination
from sklearn.datasets import load_boston
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeRegressor
X, y = load_boston(return_X_y=True)
print(X, type(X), X.shape, '\n', y, type(y), y.shape)
rfe = RFE(DecisionTreeRegressor(),5,step=1)
print(rfe)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]] <class 'numpy.ndarray'> (506, 13) 
 [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18

In [60]:
selected_by_rfe = rfe.fit_transform(X,y)
print(selected_by_rfe, type(selected_by_rfe), selected_by_rfe.shape)
print(rfe.support_)
print(rfe.ranking_)

[[6.3200e-03 5.3800e-01 6.5750e+00 4.0900e+00 4.9800e+00]
 [2.7310e-02 4.6900e-01 6.4210e+00 4.9671e+00 9.1400e+00]
 [2.7290e-02 4.6900e-01 7.1850e+00 4.9671e+00 4.0300e+00]
 ...
 [6.0760e-02 5.7300e-01 6.9760e+00 2.1675e+00 5.6400e+00]
 [1.0959e-01 5.7300e-01 6.7940e+00 2.3889e+00 6.4800e+00]
 [4.7410e-02 5.7300e-01 6.0300e+00 2.5050e+00 7.8800e+00]] <class 'numpy.ndarray'> (506, 5)
[ True False False False  True  True False  True False False False False
  True]
[1 8 6 7 1 1 3 1 9 2 4 5 1]


In [61]:
print('Prediction by RFE', rfe.predict(X), rfe.predict(X).shape, type(rfe.predict(X)))
print('y', y, y.shape)

Prediction by RFE [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.

In [62]:
import pandas as pd
boston  = pd.DataFrame(load_boston()['data'], columns=list(load_boston()['feature_names']))
boston['target'] = load_boston()['target']
print(boston)

        CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1    0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2    0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3    0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4    0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...     ...
501  0.06263   0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67    22.4
502  0.04527   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08    20.6
503  0.06076   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64    23.9
504  0.10959   0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48    22.0
505  0.04741   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88    11.9

[50

In [63]:
boston_rfe = pd.DataFrame(selected_by_rfe)
boston_rfe['old y/target'] = boston['target']
boston_rfe['y predicted by rfe'] = rfe.predict(X)
boston_rfe

0      1      2       3     4  old y/target  y predicted by rfe
0    0.00632  0.538  6.575  4.0900  4.98          24.0                24.0
1    0.02731  0.469  6.421  4.9671  9.14          21.6                21.6
2    0.02729  0.469  7.185  4.9671  4.03          34.7                34.7
3    0.03237  0.458  6.998  6.0622  2.94          33.4                33.4
4    0.06905  0.458  7.147  6.0622  5.33          36.2                36.2
..       ...    ...    ...     ...   ...           ...                 ...
501  0.06263  0.573  6.593  2.4786  9.67          22.4                22.4
502  0.04527  0.573  6.120  2.2875  9.08          20.6                20.6
503  0.06076  0.573  6.976  2.1675  5.64          23.9                23.9
504  0.10959  0.573  6.794  2.3889  6.48          22.0                22.0
505  0.04741  0.573  6.030  2.5050  7.88          11.9                11.9

[506 rows x 7 columns]

In [64]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_le = le.fit_transform(boston_rfe['y predicted by rfe'])
print(y_le.shape, type(y_le), y_le)
boston_le = pd.DataFrame(boston_rfe)
boston_le['label encoded y'] = y_le
print(boston_le)

(506,) <class 'numpy.ndarray'> [137 113 196 193 203 165 126 156  64  87  52  87 114 102  80  97 128  73
 100  80  40  94  54  48  57  42  65  50  82 108  32  48  36  35  39  87
  98 108 144 176 197 153 149 144 110  91  98  65  47  92  95 103 146 131
  87 200 144 181 130  94  85  59 119 146 189 132  92 117  72 107 139 114
 125 131 138 111  98 106 110 101 159 136 145 126 136 153 122 119 133 165
 123 117 126 146 104 162 111 211 219 191 157 152  84  91  99  93  93 102
  96  92 114 125  86  85  83  81 110  90 102  91 117 101 103  71  86 111
  58  61  78  46  90  94 127  82  57  79  72  69  37  76  43  47  38  57
  25  41  57  49  76  56 112  94  55  92  68  57  35 213 140 130 155 228
 228 228 124 146 228 135 135 120  72  89 128 133 123 168 129 143 171 207
 212 203 210 186 151 169 228 183 170 197 206 174 204 178 167 228 192 173
 195 197 188 138 215 226 228 123 141 122 141  98 114  91 121 160 134 146
 130 165 112 127 154 114 157 172 221 228 209 181 224 180 140 182 214 225
 166 137 147 180 134

In [65]:
# One Hot Encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
print(ohe)
print(pd.DataFrame(boston_rfe.iloc[:,6]))
s1 = pd.DataFrame(ohe.fit_transform(pd.DataFrame(boston_rfe.iloc[:,6])))
print(type(s1),s1)
boston_ohe = pd.concat([boston_rfe,s1], axis=1)
print(boston_ohe) # C'est Incomplete


OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)
     y predicted by rfe
0                  24.0
1                  21.6
2                  34.7
3                  33.4
4                  36.2
..                  ...
501                22.4
502                20.6
503                23.9
504                22.0
505                11.9

[506 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>                    0
0      (0, 137)\t1.0
1      (0, 113)\t1.0
2      (0, 196)\t1.0
3      (0, 193)\t1.0
4      (0, 203)\t1.0
..               ...
501    (0, 121)\t1.0
502    (0, 104)\t1.0
503    (0, 136)\t1.0
504    (0, 117)\t1.0
505     (0, 26)\t1.0

[506 rows x 1 columns]
           0      1  ...  label encoded y                0
0    0.00632  0.538  ...              137    (0, 137)\t1.0
1    0.02731  0.469  ...              113    (0, 113)\t1.0
2    0.02729  0.469  ...              196    (0, 196)\t1.0
3    0.03237

In [66]:
# One Hot Encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False) #key is to set sparse = False as the default sparse is True.
print(ohe)
print(boston.iloc[:,:-1])
boston_ohe = ohe.fit_transform(boston.iloc[:,:-1])
print(type(boston_ohe),boston_ohe)
boston_ohe_df = pd.DataFrame(boston_ohe)
print(boston_ohe_df,'\n', boston_ohe_df.describe())

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)
        CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45 

In [83]:
#get dummies
boston_dummies = pd.get_dummies(boston)
print(boston_dummies, '\n', boston_dummies.describe())

        CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  target
0    0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98    24.0
1    0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14    21.6
2    0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03    34.7
3    0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94    33.4
4    0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33    36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...     ...
501  0.06263   0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67    22.4
502  0.04527   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08    20.6
503  0.06076   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64    23.9
504  0.10959   0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48    22.0
505  0.04741   0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88    11.9

[50

In [68]:
pd.get_dummies(boston_le)

0      1      2  ...  old y/target  y predicted by rfe  label encoded y
0    0.00632  0.538  6.575  ...          24.0                24.0              137
1    0.02731  0.469  6.421  ...          21.6                21.6              113
2    0.02729  0.469  7.185  ...          34.7                34.7              196
3    0.03237  0.458  6.998  ...          33.4                33.4              193
4    0.06905  0.458  7.147  ...          36.2                36.2              203
..       ...    ...    ...  ...           ...                 ...              ...
501  0.06263  0.573  6.593  ...          22.4                22.4              121
502  0.04527  0.573  6.120  ...          20.6                20.6              104
503  0.06076  0.573  6.976  ...          23.9                23.9              136
504  0.10959  0.573  6.794  ...          22.0                22.0              117
505  0.04741  0.573  6.030  ...          11.9                11.9               26

[506 rows x 8 columns]

In [102]:
#LabelBinarizer is applied only on the target variable while one hot encoding is applied on the dataframe or features.
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
print(boston['target'])
val = boston['target'].values
print(type(val), val)
#boston_lb_y = lb.fit(val) # Not Working yet

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: target, Length: 506, dtype: float64
<class 'numpy.ndarray'> [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 

ValueError: ignored

In [69]:
#numerical to categorical binning
from sklearn.preprocessing import KBinsDiscretizer
kbd = KBinsDiscretizer()
#df1_binned = kbd.fit_transform(df1)
boston_df = pd.DataFrame(load_boston()['data'])
print(boston_df)
boston_df = boston_df.iloc[:,9:12]
print(boston_df)
boston_kbd = kbd.fit_transform(boston_df)
print(boston_kbd)

          0     1      2    3      4   ...   8      9     10      11    12
0    0.00632  18.0   2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1    0.02731   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2    0.02729   0.0   7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03
3    0.03237   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63  2.94
4    0.06905   0.0   2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90  5.33
..       ...   ...    ...  ...    ...  ...  ...    ...   ...     ...   ...
501  0.06263   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  391.99  9.67
502  0.04527   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  9.08
503  0.06076   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  5.64
504  0.10959   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  393.45  6.48
505  0.04741   0.0  11.93  0.0  0.573  ...  1.0  273.0  21.0  396.90  7.88

[506 rows x 13 columns]
        9     10      11
0    296.0  15.3  396.90
1    242.0  17.8  396.90


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 2 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)


In [70]:
print(df)
df4kbd = df.iloc[:5,[18,24]]
print(df4kbd)
kbd_binned = kbd.fit_transform(df4kbd)
print(kbd_binned)
import scipy
print(scipy.sparse.csr_matrix.toarray(kbd_binned))

      0    1          2      3      4     5   ...   22   23       24   25   26   27
0    2.0  1.0   530101.0  38.50   66.0  28.0  ...  2.0  2.0  11300.0  0.0  0.0  2.0
1    1.0  1.0   534817.0  39.20   88.0  20.0  ...  3.0  2.0   2208.0  0.0  0.0  2.0
2    2.0  1.0   530334.0  38.30   40.0  24.0  ...  1.0  2.0      0.0  0.0  0.0  1.0
3    1.0  9.0  5290409.0  39.10  164.0  84.0  ...  2.0  1.0   2208.0  0.0  0.0  1.0
4    2.0  1.0   530255.0  37.30  104.0  35.0  ...  2.0  2.0   4300.0  0.0  0.0  2.0
..   ...  ...        ...    ...    ...   ...  ...  ...  ...      ...  ...  ...  ...
295  1.0  1.0   533886.0  38.18  120.0  70.0  ...  3.0  2.0   3205.0  0.0  0.0  2.0
296  2.0  1.0   527702.0  37.20   72.0  24.0  ...  3.0  1.0   2208.0  0.0  0.0  1.0
297  1.0  1.0   529386.0  37.50   72.0  30.0  ...  2.0  1.0   3205.0  0.0  0.0  2.0
298  1.0  1.0   530612.0  36.50  100.0  24.0  ...  1.0  1.0   2208.0  0.0  0.0  1.0
299  1.0  1.0   534618.0  37.20   40.0  20.0  ...  3.0  2.0   6112.0  0.0  0

In [71]:
kbd1 = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='uniform') #ordinal and uniform are not API's original choices and we need to define these separately.
df_binned1 = kbd1.fit_transform(df4kbd)
print(df_binned1)

[[2. 9.]
 [4. 1.]
 [0. 0.]
 [3. 1.]
 [9. 3.]]


In [72]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()
boston_df_mm = minmax.fit_transform(boston_df)
print(boston_df_mm, boston_df_mm.shape)

[[0.20801527 0.28723404 1.        ]
 [0.10496183 0.55319149 1.        ]
 [0.10496183 0.55319149 0.98973725]
 ...
 [0.16412214 0.89361702 1.        ]
 [0.16412214 0.89361702 0.99130062]
 [0.16412214 0.89361702 1.        ]] (506, 3)


In [73]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
for i in cancer:
  print(i)
  print(cancer[i])

data
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
target
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 

In [74]:
print(cancer['data'].shape, cancer['data'])
print(cancer['target'].shape, cancer['target'])
print(cancer.feature_names, len(cancer.feature_names))

(569, 30) [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
(569,) [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0

In [75]:
cancer_df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
cancer_df['target'] = cancer.target
cancer_df

mean radius  mean texture  ...  worst fractal dimension  target
0          17.99         10.38  ...                  0.11890       0
1          20.57         17.77  ...                  0.08902       0
2          19.69         21.25  ...                  0.08758       0
3          11.42         20.38  ...                  0.17300       0
4          20.29         14.34  ...                  0.07678       0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[569 rows x 31 columns]

In [76]:
# Understanding One Hot Encoding in detail
print(pd.get_dummies(cancer_df['mean radius']))

     6.981   7.691   7.729   7.760   ...  25.730  27.220  27.420  28.110
0         0       0       0       0  ...       0       0       0       0
1         0       0       0       0  ...       0       0       0       0
2         0       0       0       0  ...       0       0       0       0
3         0       0       0       0  ...       0       0       0       0
4         0       0       0       0  ...       0       0       0       0
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
564       0       0       0       0  ...       0       0       0       0
565       0       0       0       0  ...       0       0       0       0
566       0       0       0       0  ...       0       0       0       0
567       0       0       0       0  ...       0       0       0       0
568       0       0       0       1  ...       0       0       0       0

[569 rows x 456 columns]


In [77]:
print(cancer.values())

dict_values([array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       

In [78]:
#print(cancer_df.values()) # Error 'numpy.ndarray' object is not callable

In [79]:
ohe1 = OneHotEncoder(sparse=False)
X_oe = ohe1.fit_transform(cancer.data)
print(X_oe.shape, type(X_oe), X_oe)
X_oe_df = pd.DataFrame(X_oe)
print(X_oe_df,'\n', X_oe_df.describe())

(569, 15340) <class 'numpy.ndarray'> [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
     0      1      2      3      4      ...  15335  15336  15337  15338  15339
0      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
1      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
2      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
3      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    1.0    0.0
4      0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
..     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
564    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
565    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
566    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0    0.0    0.0
567    0.0    0.0

In [80]:
ohe1 = OneHotEncoder(sparse=True)
X_oe = ohe1.fit_transform(cancer.data)
print(X_oe.shape, type(X_oe), X_oe)
X_oe_df = pd.DataFrame(X_oe)
print(X_oe_df,'\n', X_oe_df.describe())

(569, 15340) <class 'scipy.sparse.csr.csr_matrix'>   (0, 370)	1.0
  (0, 457)	1.0
  (0, 1390)	1.0
  (0, 1909)	1.0
  (0, 2440)	1.0
  (0, 3001)	1.0
  (0, 3528)	1.0
  (0, 4070)	1.0
  (0, 4502)	1.0
  (0, 5001)	1.0
  (0, 5542)	1.0
  (0, 5726)	1.0
  (0, 6596)	1.0
  (0, 7124)	1.0
  (0, 7414)	1.0
  (0, 8173)	1.0
  (0, 8685)	1.0
  (0, 9158)	1.0
  (0, 9704)	1.0
  (0, 10252)	1.0
  (0, 10733)	1.0
  (0, 10806)	1.0
  (0, 11773)	1.0
  (0, 12306)	1.0
  (0, 12692)	1.0
  :	:
  (568, 2507)	1.0
  (568, 3007)	1.0
  (568, 3544)	1.0
  (568, 4177)	1.0
  (568, 4666)	1.0
  (568, 5347)	1.0
  (568, 5923)	1.0
  (568, 6377)	1.0
  (568, 6761)	1.0
  (568, 7482)	1.0
  (568, 7688)	1.0
  (568, 8225)	1.0
  (568, 8758)	1.0
  (568, 9671)	1.0
  (568, 9985)	1.0
  (568, 10316)	1.0
  (568, 11152)	1.0
  (568, 11283)	1.0
  (568, 11797)	1.0
  (568, 12344)	1.0
  (568, 12762)	1.0
  (568, 13274)	1.0
  (568, 13813)	1.0
  (568, 14577)	1.0
  (568, 14926)	1.0


/usr/local/lib/python3.7/dist-packages/pandas/core/algorithms.py:797: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  keys, counts = _value_counts_arraylike(values, dropna)


                                                     0
0      (0, 370)\t1.0\n  (0, 457)\t1.0\n  (0, 1390)\...
1      (0, 426)\t1.0\n  (0, 642)\t1.0\n  (0, 1421)\...
2      (0, 406)\t1.0\n  (0, 780)\t1.0\n  (0, 1413)\...
3      (0, 98)\t1.0\n  (0, 753)\t1.0\n  (0, 1099)\t...
4      (0, 418)\t1.0\n  (0, 516)\t1.0\n  (0, 1428)\...
..                                                 ...
564    (0, 438)\t1.0\n  (0, 826)\t1.0\n  (0, 1438)\...
565    (0, 413)\t1.0\n  (0, 919)\t1.0\n  (0, 1418)\...
566    (0, 340)\t1.0\n  (0, 914)\t1.0\n  (0, 1345)\...
567    (0, 429)\t1.0\n  (0, 923)\t1.0\n  (0, 1435)\...
568    (0, 3)\t1.0\n  (0, 870)\t1.0\n  (0, 936)\t1....

[569 rows x 1 columns] 
                                                         0
count                                                 569
unique                                                569
top       (0, 416)\t1.0\n  (0, 900)\t1.0\n  (0, 1423)\...
freq                                                    1
