<a href="https://colab.research.google.com/github/ulrikSebastienR/2021-Coding-Basic/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Contents: 1. Sort a List

In [ ]:
l = [1,34, 43, 53, 12, 342, 5343]
# sort and sorted
#https://www.programiz.com/python-programming/methods/list/sort

In [ ]:
print(l.sort())# returns none but actually modifies the list
print(l)

In [ ]:
l = [1,34, 43, 53, 12, 342, 5343]
print(sorted(l)) # returns the new list but does not modify the original list
print(l)

In [ ]:
# reverse order sorting
print(l.sort(reverse=True))
l

In [ ]:
l = [1,34, 43, 53, 12, 342, 5343]
print(sorted(l, reverse= True))
l

In [ ]:
employee = [
    {'name':'Barak Obama', 'age': 58 , 'salary': 200000 },
    {'name':'Dick young', 'age': 32, 'salary': 12000 },
    {'name':'Cheney Senior', 'age': 65 , 'salary': 1200000}
]
print(type(employee))

def getnames(elem):
    return elem['name']

def getage(elem):
    return elem['age']

def salary(elem):
    return elem['salary']

for i in employee:
    print(getnames(i), getage(i), salary(i))

print(sorted(employee, key=getage, reverse=True))
print(employee.sort(key= lambda x: x.get('name')))
print(employee)

In [ ]:
#sort a dictionary 
orders = {
	'cappuccino': 54,
	'latte': 56,
	'espresso': 72,
	'americano': 48,
	'cortado': 41
}

print(list((key, value) for (key, value) in sorted(orders.items(),key = lambda x: x[0]))) # by keys
print() #by values


In [11]:
#sort a numpy array
import numpy as np
a = np.random.randint(4,100,(1,7))
print('a', a, type(a))

b = np.sort(a)
print('using the np.sort function', b, type(b))

c = np.argsort(a)
print('argsort returns only indices in original array and does not alter original array or provide a new array', c, c.shape, type(c), '\n', 'a=', a, a.shape)


a [[22 87 89 29 91 99 21]] <class 'numpy.ndarray'>
using the np.sort function [[21 22 29 87 89 91 99]] <class 'numpy.ndarray'>
argsort returns only indices in original array and does not alter original array or provide a new array [[6 0 3 1 2 4 5]] (1, 7) <class 'numpy.ndarray'> 
 a= [[22 87 89 29 91 99 21]] (1, 7)


In [19]:
l  = [
      [1,3,5,5,8,0],
      [2,34,5,9,10,2],
      [3,5,9,10,11,12]
]
print(type(l))
a = np.array(l)
print(a,type(a), a.shape)

<class 'list'>
[[ 1  3  5  5  8  0]
 [ 2 34  5  9 10  2]
 [ 3  5  9 10 11 12]] <class 'numpy.ndarray'> (3, 6)


In [20]:
np.partition(a, 2, axis=1)

array([[ 0,  1,  3,  5,  8,  5],
       [ 2,  2,  5,  9, 10, 34],
       [ 3,  5,  9, 10, 11, 12]])