<a href="https://colab.research.google.com/github/ulrikSebastienR/2021-Basic-Python/blob/main/Understanding_numpy_axes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,1000,(5,4,3,2))
x

array([[[[162, 255],
         [189, 318],
         [868, 938]],

        [[128, 325],
         [149, 729],
         [ 29, 667]],

        [[570,  36],
         [579, 696],
         [195, 655]],

        [[489, 956],
         [ 69,  34],
         [ 48, 373]]],


       [[[788,  32],
         [ 75, 275],
         [204,  87]],

        [[561, 927],
         [483, 346],
         [969, 545]],

        [[579, 193],
         [219, 127],
         [226,  36]],

        [[865, 875],
         [181, 869],
         [923, 855]]],


       [[[730, 905],
         [907, 263],
         [761, 171]],

        [[ 67, 639],
         [167, 524],
         [900, 117]],

        [[992, 712],
         [ 32, 296],
         [946, 695]],

        [[635, 234],
         [785, 166],
         [521, 847]]],


       [[[525, 622],
         [112, 402],
         [453, 556]],

        [[ 43, 205],
         [101, 763],
         [144, 215]],

        [[374,  83],
         [912, 374],
         [795, 866]],

        [[901, 292]

In [3]:
x[0,:,:,:]


array([[[162, 255],
        [189, 318],
        [868, 938]],

       [[128, 325],
        [149, 729],
        [ 29, 667]],

       [[570,  36],
        [579, 696],
        [195, 655]],

       [[489, 956],
        [ 69,  34],
        [ 48, 373]]])

In [4]:
x[1,:,:,:]

array([[[788,  32],
        [ 75, 275],
        [204,  87]],

       [[561, 927],
        [483, 346],
        [969, 545]],

       [[579, 193],
        [219, 127],
        [226,  36]],

       [[865, 875],
        [181, 869],
        [923, 855]]])

In [5]:
x[:,0,:,:]


array([[[162, 255],
        [189, 318],
        [868, 938]],

       [[788,  32],
        [ 75, 275],
        [204,  87]],

       [[730, 905],
        [907, 263],
        [761, 171]],

       [[525, 622],
        [112, 402],
        [453, 556]],

       [[276, 701],
        [746, 271],
        [249, 753]]])

In [6]:
x[:,1,:,:]

array([[[128, 325],
        [149, 729],
        [ 29, 667]],

       [[561, 927],
        [483, 346],
        [969, 545]],

       [[ 67, 639],
        [167, 524],
        [900, 117]],

       [[ 43, 205],
        [101, 763],
        [144, 215]],

       [[806, 752],
        [715, 589],
        [939, 669]]])

In [7]:
x[:,:,0,:]


array([[[162, 255],
        [128, 325],
        [570,  36],
        [489, 956]],

       [[788,  32],
        [561, 927],
        [579, 193],
        [865, 875]],

       [[730, 905],
        [ 67, 639],
        [992, 712],
        [635, 234]],

       [[525, 622],
        [ 43, 205],
        [374,  83],
        [901, 292]],

       [[276, 701],
        [806, 752],
        [854, 404],
        [ 36, 878]]])

In [8]:
x[:,:,1,:]

array([[[189, 318],
        [149, 729],
        [579, 696],
        [ 69,  34]],

       [[ 75, 275],
        [483, 346],
        [219, 127],
        [181, 869]],

       [[907, 263],
        [167, 524],
        [ 32, 296],
        [785, 166]],

       [[112, 402],
        [101, 763],
        [912, 374],
        [510, 958]],

       [[746, 271],
        [715, 589],
        [388,  77],
        [748, 272]]])

In [9]:
x[:,:,:,0]


array([[[162, 189, 868],
        [128, 149,  29],
        [570, 579, 195],
        [489,  69,  48]],

       [[788,  75, 204],
        [561, 483, 969],
        [579, 219, 226],
        [865, 181, 923]],

       [[730, 907, 761],
        [ 67, 167, 900],
        [992,  32, 946],
        [635, 785, 521]],

       [[525, 112, 453],
        [ 43, 101, 144],
        [374, 912, 795],
        [901, 510, 738]],

       [[276, 746, 249],
        [806, 715, 939],
        [854, 388, 581],
        [ 36, 748, 851]]])

In [10]:
x[:,:,:,1]

array([[[255, 318, 938],
        [325, 729, 667],
        [ 36, 696, 655],
        [956,  34, 373]],

       [[ 32, 275,  87],
        [927, 346, 545],
        [193, 127,  36],
        [875, 869, 855]],

       [[905, 263, 171],
        [639, 524, 117],
        [712, 296, 695],
        [234, 166, 847]],

       [[622, 402, 556],
        [205, 763, 215],
        [ 83, 374, 866],
        [292, 958, 892]],

       [[701, 271, 753],
        [752, 589, 669],
        [404,  77, 999],
        [878, 272, 382]]])

In [11]:
x=np.random.randint(1,100,(4,3,2))
x

array([[[33, 42],
        [35, 24],
        [22, 11]],

       [[43, 17],
        [53, 10],
        [43, 35]],

       [[98, 94],
        [97, 40],
        [81, 54]],

       [[56,  7],
        [88, 71],
        [99, 67]]])

In [12]:
x[0,:,:]


array([[33, 42],
       [35, 24],
       [22, 11]])

In [13]:
x[1,:,:]

array([[43, 17],
       [53, 10],
       [43, 35]])

In [14]:
x[:,0,:]


array([[33, 42],
       [43, 17],
       [98, 94],
       [56,  7]])

In [15]:
x[:,1,:]

array([[35, 24],
       [53, 10],
       [97, 40],
       [88, 71]])

In [16]:
x[:,:,0]


array([[33, 35, 22],
       [43, 53, 43],
       [98, 97, 81],
       [56, 88, 99]])

In [17]:
x[:,:,1]

array([[42, 24, 11],
       [17, 10, 35],
       [94, 40, 54],
       [ 7, 71, 67]])